### ISSUE TITLE
Request your help!

### ISSUE THREAD

**Issue by ravirathore** [casualwriter/casual-markdown-doc#1]
@casualwriter 
Hi,
I tried running following code,  but couldnt get proper output (pls see image below). Request your help.

```
<!DOCTYPE html>
<link  href="https://casualwriter.github.io/dist/casual-markdown-doc.css" rel="stylesheet">
<script src="https://casualwriter.github.io/dist/casual-markdown-doc.js"></script>
<body title="Supported Syntax of Casual-Markdown">
-----------------------------------------------------------------------------

title   : Casual Markdown
github  : https://github.com/casualwriter/casual-markdown

-----------------------------------------------------------------------------
    
## {{ title }}
    
[casual-markdown]({{github}}) is a super lightweight RegExp-based markdown parser, with TOC and scrollspy support

```
![Capture96](https://user-images.githubusercontent.com/19185692/183059040-9f9aa683-18b4-44dd-a378-165bd42b3de0.PNG)

In the html output, {{title}} didn't display and link ( [casual-markdown]({{github}}) ) also didnt render.

Please advise, if I am making a mistake somewhere.

Thanks,

**Comment by casualwriter** [comment]
thanks, just fix it. please check again.

ps: frontmatter should be start at first line, but the  body content has \n in the begining. just add some code to remove the first \n to get around it.

 feel free to let me know if have any problem. thanks,

**Comment by ravirathore** [comment]
Thanks. Great, its working.

Thanks a lot,
Best of luck,
